<?php

namespace Dojo_PHP;
use Dojo_PHP\ApiException;

class WebHooksUtil {

    /**
     * Validates dojo-signature for webhook payload (https://docs.dojo.tech/payments/development-resources/webhooks#step-3-verify-dojo-webhooks)
     *
     * @param string $requestBody   Raw JSON request body from the webhook request.
     * @param string $secret Raw    Secret generated by for this webhook registration.
     * @param string $dojoSignature Dojo signature that comes with the request.
     * @return void Throws, if validation fails.
     */
    public static function validatePayloadSignature($requestBody, $secret, $dojoSignature) {
        
        if (empty($requestBody)) {
            throw new ApiException("Request body value is not provided");
        }

        if (empty($secret)) {
            throw new ApiException("Secret value is not provided");
        }

        if (empty($dojoSignature)) {
            throw new ApiException("'dojo-signature' value is not provided");
        }
        
        // "sha256=EE-A5-9D-30-4D-BB-..." ->
        // eea59d4dbb...
        $dojoSignature = str_replace("sha256=", '', $dojoSignature);
        $dojoSignature = str_replace("-", '', $dojoSignature);
        $dojoSignature = strtolower($dojoSignature);

        $res = hash_hmac('sha256', $requestBody, $secret);

        if (!hash_equals($res, $dojoSignature)) {
            throw new ApiException("Signature provided in 'dojo-signature' is incorrect!");
        }
    }
}